# Generated by Django 5.2.9 on 2026-02-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
